# Generated by Django 3.1.3 on 2023-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cellphone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
